using Microsoft.Extensions.Logging;
using SMACD.Workspace.Actions;
using SMACD.Workspace.Artifacts;
using SMACD.Workspace.Libraries;
using SMACD.Workspace.Targets;
using SMACD.Workspace.Tasks;
using System.Collections.Generic;

namespace SMACD.Workspace
{
    /// <summary>
    /// Workspace linking Toolboxes, Artifacts, Reports, and Actions
    /// </summary>
    public class Workspace
    {
        /// <summary>
        /// Actions available in the system to execute
        /// </summary>
        public ActionToolbox Actions { get; }

        /// <summary>
        /// Libraries loaded in the system
        /// </summary>
        public LibraryToolbox Libraries { get; }

        /// <summary>
        /// Targets available to act upon, and registration for new Targets
        /// </summary>
        public TargetToolbox Targets { get; }

        /// <summary>
        /// Tasks running in this operation, and enqueue ability
        /// </summary>
        public TaskToolbox Tasks { get; }

        /// <summary>
        /// Triggers registered in this system
        /// </summary>
        public TriggerToolbox Triggers { get; }

        /// <summary>
        /// Root of artifact tree
        /// </summary>
        public Artifact Artifacts { get; }

        /// <summary>
        /// Reports generated by elements in this Workspace
        /// </summary>
        public List<ActionSpecificReport> Reports { get; } = new List<ActionSpecificReport>();

        protected ILogger Logger { get; set; }

        /// <summary>
        /// Creates a new Workspace wrapping a given Artifact root
        /// </summary>
        /// <param name="artifactRoot">Artifact root</param>
        public Workspace(Artifact artifactRoot)
        {
            Artifacts = artifactRoot;

            Actions = new ActionToolbox(this);
            Targets = new TargetToolbox(this);
            Libraries = new LibraryToolbox(this);
            Tasks = new TaskToolbox(this);
            Triggers = new TriggerToolbox(this);
        }
    }
}
