using System.Threading.Tasks;

namespace SMACD.ScannerEngine.Plugins
{
    public abstract class ScorerPlugin : Plugin
    {
        /// <summary>
        /// Score the artifacts generated by an Attack Tool
        /// </summary>
        /// <param name="summary">Summary report that contains plugin scores</param>
        /// <returns></returns>
        public abstract Task Score(VulnerabilitySummary summary);

        /// <summary>
        /// Converge the summary report by running it until all Plugins report that
        /// they have not made any changes to the summary
        /// </summary>
        /// <param name="summary">Summary report</param>
        /// <returns><c>TRUE</c> if changes were made to the report, otherwise <c>FALSE</c></returns>
        public abstract Task<bool> Converge(VulnerabilitySummary summary);
    }
}