using System.Collections.Generic;
using YamlDotNet.Serialization;

namespace SMACD.Data
{
    /// <summary>
    ///     Represents a Resource resolved to its handler
    /// </summary>
    public abstract class Resource : IModel
    {
        protected Resource()
        {
            SystemCreated = true;
        }

        protected Resource(string resourceId)
        {
            ResourceId = resourceId;
        }

        /// <summary>
        ///     Resource identifier
        /// </summary>
        public string ResourceId { get; set; }

        /// <summary>
        ///     If the Resource was generated by the system
        /// </summary>
        public bool SystemCreated { get; set; }

        /// <summary>
        /// Instances of the Resource base
        /// </summary>
        [YamlIgnore]
        public IList<Resource> Instances { get; } = new List<Resource>();

        /// <summary>
        ///     Retrieve a string that represents the target of this resource
        /// </summary>
        /// <returns></returns>
        public abstract string GetDescription();

        /// <summary>
        ///     Retrieve the resource with given transformations
        /// </summary>
        /// <param name="parameters">Parameters to pass to Resource</param>
        /// <returns></returns>
        public virtual Resource GetWithParameters(IDictionary<string, string> parameters)
        {
            return this;
        }
    }
}