namespace Synthesys.SDK.Extensions
{
    /// <summary>
    ///     An ActionExtension is generated from known information about a system. ActionExtensions are imported into the
    ///     Artifact Tree in the same way as any discovered data. The intent is for the framework to use the information
    ///     generated by ActionExtensions to create ReactionExtensions.
    /// </summary>
    public abstract class ActionExtension : Extension
    {
        /// <summary>
        ///     This method is called when the ActionExtension is popped from the Task Queue and executed
        /// </summary>
        /// <returns></returns>
        public abstract ExtensionReport Act();
    }
}